version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"   # Host port 3001 maps to container's 3000

  backend:
    build: ./backend
    ports:
      - "3002:3000"   # Host port 3002 maps to container's 3000
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    volumes:
      - ./backend:/app  # Mounts local backend files for development
    command: npm run dev

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
